# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nXE1BLLG5NH1LBu5vr9hj1Fz34fBxG8p
"""

import pandas as pd
import numpy as np
import io

from google.colab import files 
uploaded= files.upload()

df=pd.read_csv(io.StringIO(uploaded['POWER_Point_Daily_20190101_20210305_022d6471N_077d9231E_LST.csv'].decode('utf-8')))

df.head()

import fbprophet

df.describe()

df.dtypes

df.info()

df.isnull().count()

import datetime

df["YEAR"]=df["YEAR"].astype(str)
df["MO"]=df["MO"].astype(str)
df["DY"]=df["DY"].astype(str)
df

df["Date"]=pd.to_datetime(df["YEAR"] + "/" + df["MO"] + "/" + df["DY"])
df

df.drop('MO',inplace=True,axis=1)
df.drop('DY',inplace=True,axis=1)
df.drop('YEAR',inplace=True,axis=1)

df

df.info()

import matplotlib.pyplot as plt

df['temp'] = df['T2M']
df.head()

df.drop('T2M',inplace=True,axis=1)

df

df.columns = ['ds','y']
df.head()

from fbprophet import Prophet

model=Prophet()
model.fit(df)

model.component_modes

future_dates=model.make_future_dataframe(periods=365)

future_dates.tail()

prediction=model.predict(future_dates)

prediction.head()

prediction

model.plot(prediction)

model.plot_components(prediction)

from fbprophet.diagnostics import cross_validation
df_cv = cross_validation(model,initial = "365 days",period="180 days" ,horizon = "365 days")
df_cv.head()

from fbprophet.diagnostics import performance_metrics
df_p = performance_metrics(df_cv)
df_p.head()

from fbprophet.plot import plot_cross_validation_metric
fig = plot_cross_validation_metric(df_cv, metric='rmse')

